services:
  postgres:
    image: postgres:16-alpine
    container_name: delivery_postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: delivery_db
      POSTGRES_USER: delivery_user
      POSTGRES_PASSWORD: delivery_pass
    volumes:
      - delivery_postgres_data:/var/lib/postgresql/data

volumes:
  delivery_postgres_data:
